version: "3.9"

services:
  web:
    build: .
    command: python /zaverecny_projekt/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/zaverecny_projekt
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hudba
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: