# Generated by Django 4.0.4 on 2022-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(to='hudba.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
