# Generated by Django 4.0.4 on 2022-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0002_remove_artist_genre_artist_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='hudba.genre'),
        ),
    ]
