# Generated by Django 4.0.4 on 2022-05-17 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0003_remove_album_genre_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hudba.album'),
            preserve_default=False,
        ),
    ]
