# Generated by Django 4.0.4 on 2022-05-21 07:02
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0006_alter_album_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date']},
        ),
        migrations.AddField(
            model_name='album',
            name='length',
            field=models.DurationField(default=datetime.timedelta(days=-1, seconds=68400)),
            preserve_default=False,
        ),
    ]
