# Generated by Django 4.0.4 on 2022-05-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0007_alter_album_options_album_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['rating']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['number']},
        ),
    ]
