# Generated by Django 4.0.4 on 2022-11-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0011_alter_album_about_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='hudba.genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hudba.label'),
        ),
        migrations.AlterField(
            model_name='album',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
