# Generated by Django 4.0.4 on 2022-11-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0013_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='hudba.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='hudba.label'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='hudba.members'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hudba.origin'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_begin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
