# Generated by Django 4.0.4 on 2022-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0014_alter_artist_about_alter_artist_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
