# Generated by Django 4.0.4 on 2022-12-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0016_alter_album_about_alter_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['-role__name']},
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
